version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: credits-api
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "465:465"
    volumes:
      - credits-data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - credits-network

# 添加 Docker 镜像构建加速配置
x-build-args: &build-args
  DOCKER_BUILDKIT: 1
  BUILDKIT_INLINE_CACHE: 1
  DOCKER_CLI_EXPERIMENTAL: enabled
  DOCKER_REGISTRY_MIRROR: https://registry.docker-cn.com

  # 如果需要数据库服务，可以取消注释以下部分
  # db:
  #   image: postgres:14-alpine
  #   container_name: credits-db
  #   restart: unless-stopped
  #   environment:
  #     - POSTGRES_USER=${DB_USER}
  #     - POSTGRES_PASSWORD=${DB_PASSWORD}
  #     - POSTGRES_DB=${DB_NAME}
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   networks:
  #     - credits-network

volumes:
  credits-data:
  # postgres-data:

networks:
  credits-network:
    driver: bridge
